# Generated by Django 4.0.1 on 2022-01-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_post_published_date_alter_post_pub_date_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='view',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date_post',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
